CREATE TABLE odot_category(
  id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  when_created DATE NOT NULL DEFAULT CURRENT_DATE,
  when_last_updated DATE NOT NULL DEFAULT CURRENT_DATE,
  name VARCHAR(64) NOT NULL UNIQUE,
  description VARCHAR(128) NOT NULL
  );

CREATE TABLE odot_item(
  id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  when_created DATE NOT NULL DEFAULT CURRENT_DATE,
  when_last_updated DATE NOT NULL DEFAULT CURRENT_DATE,
  description VARCHAR(128) NOT NULL UNIQUE,
  due_date DATE NOT NULL DEFAULT CURRENT_DATE,
  finished BOOLEAN NOT NULL DEFAULT FALSE,
  category_id INTEGER REFERENCES odot_category(id)
  );
  